version: '3.8'

services:
    traefik:
        image: traefik:v3.5.0
        container_name: traefik
        restart: unless-stopped
        networks:
            - traefik-network
        ports:
            - "80:80"
            - "443:443"
        command:
            - "--providers.docker=true"
            - "--providers.docker.network=traefik-network"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
            - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
            - "--log.level=DEBUG"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik:/traefik

    database:
        image: postgres:15
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./database:/var/lib/postgresql/data
        networks:
            - nextcloud-network

    nextcloud:
        image: nextcloud:latest
        container_name: nextcloud-aio-mastercontainer
        restart: unless-stopped
        environment:
            POSTGRES_HOST: database
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
            NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
            NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_HOST}
            TRUSTED_PROXIES: ${NEXTCLOUD_TRUSTED_PROXIES}
            OVERWRITEHOST: ${NEXTCLOUD_HOST}
            OVERWRITEPROTOCOL: https
            APACHE_PORT: 80
            APACHE_ADDITIONAL_NETWORK: traefik-network
        volumes:
            - ./nextcloud/src:/var/www/html
            - ./nextcloud/data:/var/www/html/data
        networks:
            - nextcloud-network
            - traefik-network
        depends_on:
            - database
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-network"
            - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST}`)"
            - "traefik.http.routers.nextcloud.entrypoints=websecure"
            - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
            - "traefik.http.routers.nextcloud-http.rule=Host(`${NEXTCLOUD_HOST}`)"
            - "traefik.http.routers.nextcloud-http.entrypoints=web"
            - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-redirect"
            - "traefik.http.middlewares.nextcloud-redirect.redirectscheme.scheme=https"

volumes:
    database:
        driver: local
    nextcloud_src:
        driver: local

networks:
    traefik-network:
        external: true
    nextcloud-network:
